version: "3.8"
services:
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - cultilytics-uploads:/app/public/uploads
    env_file:
      - .env
  client-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    volumes:
      - cultilytics-uploads:/app/public/uploads
      - /app/.data
    env_file:
      - .env

volumes:
  cultilytics-uploads:
